name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Docker Semver
        uses: mirzamerdovic/docker-semver-github-action@master
        with:
          name: mirzamerdovic/shower
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile:  ./src/Dockerfile 
          context: ./src
